# fly.toml app configuration file generated for telegram-echo-bot-luis on 2025-04-25T17:59:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegram-echo-bot-luis'
primary_region = 'sea'

[experimental]
  auto_rollback = true

[build]

[env]
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
