name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Log in to Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: parentplannerace-ddcqcth4gtg8csc5.azurecr.io

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t parentplannerace-ddcqcth4gtg8csc5.azurecr.io/parent-planner:latest .
          docker push parentplannerace-ddcqcth4gtg8csc5.azurecr.io/parent-planner:latest

      # Deploy to Azure Web App for Containers
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'ParentPlannerWebApp'
          images: 'parentplannerace-ddcqcth4gtg8csc5.azurecr.io/parent-planner:latest'